#ifndef AURA_SERVER_DEFAULTS
#define AURA_SERVER_DEFAULTS

#define A_DEF_MAX_REQ_SZ 1024 * 1024 * 1024
#define A_DEF_HANDSHAKE_TIMEOUT 10 /* seconds */
#define A_DEF_H2_IDLE_TIMEMOUT 10  /* seconds */
#define A_DEF_H2_GRACEFUL_SHUTDOWN_TIMEOUT 0
#define A_DEF_H2_SETTING_MAX_CONCURRENT_STREAMS 100
#define A_DEF_H2_ACTIVE_STREAM_WINDOW_SZ 16 * 1024 * 1024 /* 16KB */

#endif