#ifndef AURA_TOKEN_H
#define AURA_TOKEN_H

#include <stdbool.h>
#include <stdint.h>
#include <sys/uio.h>

#include "types_lib.h"

#define A_MAX_TOKENS 100

typedef enum {
    AURA_TOKEN_NO_COMPRESS = 0,
    AURA_TOKEN_NO_INDEX
} aura_token_flags;

typedef enum {
    A_TOKEN_NONE = 0,
    A_TOKEN_AUTHORITY = 1,
    A_TOKEN_METHOD = 2,
    A_TOKEN_PATH = 4,
    A_TOKEN_SCHEME = 6,
    A_TOKEN_STATUS = 8,
    A_TOKEN_ACCEPT_CHARSET = 15,
    A_TOKEN_ACCEPT_ENCODING = 16,
    A_TOKEN_ACCEPT_LANGUAGE = 17,
    A_TOKEN_ACCEPT_RANGES = 18,
    A_TOKEN_ACCEPT = 19,
    A_TOKEN_ACCESS_CONTROL_ALLOW_ORIGIN = 20,
    A_TOKEN_AGE = 21,
    A_TOKEN_ALLOW = 22,
    A_TOKEN_AUTHORIZATION = 23,
    A_TOKEN_CACHE_CONTROL = 24,
    A_TOKEN_CONTENT_DISPOSITION = 25,
    A_TOKEN_CONTENT_ENCODING = 26,
    A_TOKEN_CONTENT_LANGUAGE = 27,
    A_TOKEN_CONTENT_LENGTH = 28,
    A_TOKEN_CONTENT_LOCATION = 29,
    A_TOKEN_CONTENT_RANGE = 30,
    A_TOKEN_CONTENT_TYPE = 31,
    A_TOKEN_COOKIE = 32,
    A_TOKEN_DATE = 33,
    A_TOKEN_ETAG = 34,
    A_TOKEN_EXPECT = 35,
    A_TOKEN_EXPIRES = 36,
    A_TOKEN_FROM = 37,
    A_TOKEN_HOST = 38,
    A_TOKEN_IF_MATCH = 39,
    A_TOKEN_IF_MODIFIED_SINCE = 40,
    A_TOKEN_IF_NONE_MATCH = 41,
    A_TOKEN_IF_RANGE = 42,
    A_TOKEN_IF_UNMODIFIED_SINCE = 43,
    A_TOKEN_LAST_MODIFIED = 44,
    A_TOKEN_LINK = 45,
    A_TOKEN_LOCATION = 46,
    A_TOKEN_MAX_FORWARDS = 47,
    A_TOKEN_PROXY_AUTHENTICATE = 48,
    A_TOKEN_PROXY_AUTHORIZATION = 49,
    A_TOKEN_RANGE = 50,
    A_TOKEN_REFERER = 51,
    A_TOKEN_REFRESH = 52,
    A_TOKEN_RETRY_AFTER = 53,
    A_TOKEN_SERVER = 54,
    A_TOKEN_SET_COOKIE = 55,
    A_TOKEN_STRICT_TRANSPORT_SECURITY = 56,
    A_TOKEN_TRANSFER_ENCODING = 57,
    A_TOKEN_USER_AGENT = 58,
    A_TOKEN_VARY = 59,
    A_TOKEN_VIA = 60,
    A_TOKEN_WWW_AUTHENTICATE = 61,
    A_TOKEN_TE,
    A_TOKEN_PROTOCOL,
    A_TOKEN_EARLY_DATA,
    A_TOKEN_KEEP_ALIVE,
    A_TOKEN_CONNECTION,
    A_TOKEN_PRIORITY
} aura_token;

#include "token_table_lib.h"

#endif