#ifndef AURA_TOKEN_H
#define AURA_TOKEN_H

#include <stdbool.h>
#include <stdint.h>
#include <sys/uio.h>

#include "types_lib.h"

#define A_MAX_TOKENS 100

typedef enum {
    A_TOKEN_NONE = 0,
    A_TOKEN_AUTHORITY,
    A_TOKEN_METHOD,
    A_TOKEN_PATH,
    A_TOKEN_SCHEME,
    A_TOKEN_STATUS,
    A_TOKEN_ACCEPT_CHARSET,
    A_TOKEN_ACCEPT_ENCODING,
    A_TOKEN_ACCEPT_LANGUAGE,
    A_TOKEN_ACCEPT_RANGES,
    A_TOKEN_ACCEPT,
    A_TOKEN_ACCESS_CONTROL_ALLOW_ORIGIN,
    A_TOKEN_AGE,
    A_TOKEN_ALLOW,
    A_TOKEN_AUTHORIZATION,
    A_TOKEN_CACHE_CONTROL,
    A_TOKEN_CONTENT_DISPOSITION,
    A_TOKEN_CONTENT_ENCODING,
    A_TOKEN_CONTENT_LANGUAGE,
    A_TOKEN_CONTENT_LENGTH,
    A_TOKEN_CONTENT_LOCATION,
    A_TOKEN_CONTENT_RANGE,
    A_TOKEN_CONTENT_TYPE,
    A_TOKEN_COOKIE,
    A_TOKEN_DATE,
    A_TOKEN_ETAG,
    A_TOKEN_EXPECT,
    A_TOKEN_EXPIRES,
    A_TOKEN_FROM,
    A_TOKEN_HOST,
    A_TOKEN_IF_MATCH,
    A_TOKEN_IF_MODIFIED_SINCE,
    A_TOKEN_IF_NONE_MATCH,
    A_TOKEN_IF_RANGE,
    A_TOKEN_IF_UNMODIFIED_SINCE,
    A_TOKEN_LAST_MODIFIED,
    A_TOKEN_LINK,
    A_TOKEN_LOCATION,
    A_TOKEN_MAX_FORWARDS,
    A_TOKEN_PROXY_AUTHENTICATE,
    A_TOKEN_PROXY_AUTHORIZATION,
    A_TOKEN_RANGE,
    A_TOKEN_REFERER,
    A_TOKEN_REFRESH,
    A_TOKEN_RETRY_AFTER,
    A_TOKEN_SERVER,
    A_TOKEN_SET_COOKIE,
    A_TOKEN_STRICT_TRANSPORT_SECURITY,
    A_TOKEN_TRANSFER_ENCODING,
    A_TOKEN_USER_AGENT,
    A_TOKEN_VARY,
    A_TOKEN_VIA,
    A_TOKEN_WWW_AUTHENTICATE, /* static table boundary */
    A_TOKEN_TE,
    A_TOKEN_PROTOCOL,
    A_TOKEN_EARLY_DATA,
    A_TOKEN_KEEP_ALIVE,
    A_TOKEN_CONNECTION,
    A_TOKEN_PRIORITY
} aura_hpack_token_t;

#include "token_table_lib.h"

#endif