#ifndef AURA_HTTP_H
#define AURA_HTTP_H

/* Method */
typedef enum {
    HTTP_NONE,
    HTTP_GET,
    HTTP_POST,
    HTTP_PUT,
    HTTP_DELETE,
    HTTP_PATCH,
    HTTP_HEAD,
} a_http_method_t;

/* Scheme */
typedef enum {
    SCHEME_NONE,
    SCHEME_HTTP,
    SCHEME_HTTPS
} a_http_scheme_t;

/* Transport protocol */
typedef enum {
    A_PROTOCOL_NONE,
    A_PROTOCOL_TCP,
    A_PROTOCOL_UDP
} a_transport_protocol;

/* Response code */
typedef enum {
    A_HTTP_OK = 200,
    A_HTTP_CREATED = 201,
    A_HTTP_ACCEPTED = 202,
    A_HTTP_NO_CONTENT = 204,
    A_HTTP_PARTIAL_CONTENT = 206,

    A_HTTP_SPECIAL_RESPONSE = 300,
    A_HTTP_MOVED_PERMANENTLY = 301,
    A_HTTP_MOVED_TEMPORARILY = 302,
    A_HTTP_SEE_OTHER = 303,
    A_HTTP_NOT_MODIFIED = 304,
    A_HTTP_TEMPORARY_REDIRECT = 307,
    A_HTTP_PERMANENT_REDIRECT = 308,

    A_HTTP_BAD_REQUEST = 400,
    A_HTTP_UNAUTHORIZED = 401,
    A_HTTP_FORBIDDEN = 403,
    A_HTTP_NOT_FOUND = 404,
    A_HTTP_NOT_ALLOWED = 405,
    A_HTTP_REQUEST_TIME_OUT = 408,
    A_HTTP_CONFLICT = 409,
    A_HTTP_LENGTH_REQUIRED = 411,
    A_HTTP_PRECONDITION_FAILED = 412,
    A_HTTP_REQUEST_ENTITY_TOO_LARGE = 413,
    A_HTTP_REQUEST_URI_TOO_LARGE = 414,
    A_HTTP_UNSUPPORTED_MEDIA_TYPE = 415,
    A_HTTP_RANGE_NOT_SATISFIABLE = 416,
    A_HTTP_MISDIRECTED_REQUEST = 421,
    A_HTTP_TOO_MANY_REQUESTS = 429,

    A_HTTP_INTERNAL_SERVER_ERROR = 500,
    A_HTTP_NOT_IMPLEMENTED = 501,
    A_HTTP_BAD_GATEWAY = 502,
    A_HTTP_SERVICE_UNAVAILABLE = 503,
    A_HTTP_GATEWAY_TIME_OUT = 504,
    A_HTTP_VERSION_NOT_SUPPORTED = 505,
    A_HTTP_INSUFFICIENT_STORAGE = 507,
} a_http_resp_code_t;

#endif